apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo-2
  namespace: quotaz
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "800Mi"   # 0.8 GiB
        cpu: "800m"       # 0.8 CPU
      requests:
        memory: "600Mi"   # 0.6 GiB
        cpu: "400m"       # 0.4 CPU
